travis:
  secure:
    BINSTAR_TOKEN: ThaN1nuR382cVbBzR3UoHtjwNgXJ9GRCIH1AMo0aYoaeqSKl/cGVhI5Fnlb/0IiLphYE2x1WdXAFTzukE5Zj7bYkLtvuh5WztzNoBrqcCUKbTw7Eds0y4XDv0XNWrGhKKSdMmJKn6pRcp6+oSYkMTbCy9pdMPiHd6MmfL3f0W5L6rqDAkwIEwPkbTyKhQzFxAlddTB97cF84XQwYJ98oIAPf7XBKCv81f4nXdwv+jvvlOQHgPy5lsDuEbTtVSitpf/DxepEmhHbj7D+VSPu/okaRTrmbdSWeXBeY2NGqA+vl4Dudl9d6pshDyIbIhj3CRS099Ph0uoK0gkZR99H1Xgemm7V8C4NhA2RPHPXlGNPlaiqcYjgCk9Ele/QH1rlOnzS2k+1X5VcwzgKNiaMr9AgOnUg1gxPJ8pOFeNfN/N20HW+S5+ziwkb2r66Ql0fwGFxSjFjVY3H6PI/2Xk53wKl6jcj74/vnKmW3ArvioUmWeasK2uLgOiRklTa/m0k+2RRVUswy0GkbcDexBjDt+cd/QJLQvcSMa+KekQm/FpGeLcDv5tkou//fLMQ8YsCTFQOp3ODyDomh7qX36YadBsPQyRp4AF1307wHM7SaBq9fJZWzVfPp6q4J64yutd1Tevw5sP/Mw+OovlANflypUzIJQvLNLNy4hD5ET53hInQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
