travis:
  secure:
    BINSTAR_TOKEN: sJPIhBxx6kzfg55+/Hj7RB/DFLmpfvxcd48NfiSIw2qPV/Glhn02ypX34cxAUclbvNxHMF7MvKJpoW1hfsxejmt+FGhnBWEFwPyTqZot2L2KfaznEaVacq70oRdjV8czepuqVFUf0trzyzqx7RcOBHS71Qqan9HlZtEatTyIDaeZiTuJ1X93KotKiLn4UDjo8JSV7lFrGD/qva+bx3fdz8lGQTcTy6V7jNMSux3FqLtHdIdbxEVOriL7RyXMKxGX7Eyi5cL89g9gBvHkMijUqijmUNIfP+FoY4NmV6dWWPu2eaJRUn9+dUkHBpoFfslnguzk0BTPXSRR4RgvW0TQ9Ao+YYsuX55vJKof0sV/IG28gC+9NhzETwwZS/s7aEl831MoVjaQ3uE2tEnAuS9FwFYPig7PIhs6cH7a3ZHYLfPmS8WyPfbWcru6oFN7On/mIVfXIoQvxsT2/2g7pPxiR51PHovtwFPgDTul2k6zJvbIuBvaqzOuXebhqzMbuiP2wY8QIrL79IuZEJyJSgEVn9pGgBSaEDSuXC/B8cVD/2GnY8egPWKhW6KhES+FTCnG4iN3pUg2fJlMDkZvZITj7dy0I+JO93Gn15jGRx4T6HqT3rgiGz6YbsC186F0KTjpH/c+iftAXez2ehIf89qYwYxzjqFE3z/3NKJpTuCNF+w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
